In [1]:
import torch
import os
model_path = r"E:\Yiling\at_SIAT_research\z_result\20240516_1_train_binary_weight\train_dwq_sentinel2_cls_1\unet_epoch40_best_val.pth"
model_chdir = r'C:\Users\ZT\OneDrive\Studying\Yiling\00Research\202401_experiment\code'
model_device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
os.chdir(model_chdir)
model = torch.load(model_path)
model.eval()

UNet(
  (inc): double_conv(
    (conv): Sequential(
      (0): Conv2d(4, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU(inplace=True)
      (3): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (4): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (5): ReLU(inplace=True)
    )
  )
  (down1): double_down_max(
    (mpconv): Sequential(
      (0): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
      (1): double_conv(
        (conv): Sequential(
          (0): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU(inplace=True)
          (3): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (4): BatchNorm2d(128, eps=1e-05, momentum=0.1,

In [2]:
# 获取模型的第一个参数
first_param = next(model.parameters())

# 打印这个参数的设备
print(first_param.device)

cuda:0


In [5]:
# 获取模型的所有参数
state_dict = model.state_dict()
for key in state_dict.keys():
    print(key)

inc.conv.0.weight
inc.conv.0.bias
inc.conv.1.weight
inc.conv.1.bias
inc.conv.1.running_mean
inc.conv.1.running_var
inc.conv.1.num_batches_tracked
inc.conv.3.weight
inc.conv.3.bias
inc.conv.4.weight
inc.conv.4.bias
inc.conv.4.running_mean
inc.conv.4.running_var
inc.conv.4.num_batches_tracked
down1.mpconv.1.conv.0.weight
down1.mpconv.1.conv.0.bias
down1.mpconv.1.conv.1.weight
down1.mpconv.1.conv.1.bias
down1.mpconv.1.conv.1.running_mean
down1.mpconv.1.conv.1.running_var
down1.mpconv.1.conv.1.num_batches_tracked
down1.mpconv.1.conv.3.weight
down1.mpconv.1.conv.3.bias
down1.mpconv.1.conv.4.weight
down1.mpconv.1.conv.4.bias
down1.mpconv.1.conv.4.running_mean
down1.mpconv.1.conv.4.running_var
down1.mpconv.1.conv.4.num_batches_tracked
down2.mpconv.1.conv.0.weight
down2.mpconv.1.conv.0.bias
down2.mpconv.1.conv.1.weight
down2.mpconv.1.conv.1.bias
down2.mpconv.1.conv.1.running_mean
down2.mpconv.1.conv.1.running_var
down2.mpconv.1.conv.1.num_batches_tracked
down2.mpconv.1.conv.3.weight
down2.mpco

In [8]:
print(state_dict["outc.weight"].shape)
print(state_dict["outc.bias"].shape)
print(state_dict["outc.weight"].device)

torch.Size([2, 64, 1, 1])
torch.Size([2])
cuda:0


In [9]:
outc_weight = state_dict["outc.weight"].permute(2,3,0,1).reshape(-1,64).cpu()
outc_bias = state_dict["outc.bias"].cpu()
print(outc_weight.shape, outc_bias.shape)
print(outc_weight.device, outc_bias.device)
print(outc_weight)
print(outc_bias)


torch.Size([2, 64]) torch.Size([2])
cpu cpu
tensor([[-2.1675e-01, -6.9027e-02,  2.2537e-01,  1.6369e-01,  7.1990e-02,
         -2.2236e-01,  1.3891e-02, -2.5279e-01,  2.1434e-01,  2.5800e-01,
         -1.1066e-01,  1.7322e-01,  9.3752e-02, -6.4197e-03, -2.4678e-01,
          2.8659e-02,  1.2905e-01, -2.1358e-01,  2.5415e-01,  3.3753e-02,
         -8.8928e-02,  2.7337e-01, -4.2065e-02, -7.8349e-02,  5.1159e-02,
         -1.7291e-01, -9.8095e-02,  2.4632e-01, -1.5548e-01, -1.4160e-01,
          2.4535e-01, -1.5957e-01, -1.7582e-01,  2.7968e-01,  2.9241e-01,
         -1.2004e-01,  3.1860e-01, -5.5157e-02,  2.6791e-01, -2.0314e-01,
         -1.0577e-01,  1.9460e-01,  3.0574e-01, -9.0591e-02,  1.1056e-01,
          2.7079e-01, -4.7577e-02, -1.3281e-01,  2.8800e-01, -8.1104e-02,
         -4.2086e-02,  1.0749e-01,  1.9452e-01,  1.4450e-01, -1.8513e-01,
         -2.2104e-01, -1.5867e-01, -1.9658e-01,  1.3051e-01,  1.9936e-02,
         -4.7339e-02,  3.1142e-01, -1.8608e-02,  2.7607e-01],
      

In [10]:
# 创建一个列表
lst = [50, 20, 30, 10, 40]

# 对列表进行降序排序
sorted_lst = sorted(lst, reverse=True)

# 获取原列表中每个元素在排序后列表中的位置
ranks = [sorted_lst.index(x) for x in lst]

print(ranks)
# 输出：[0, 3, 2, 4, 1]

[0, 3, 2, 4, 1]


In [11]:
def get_rank(lst):
    sorted_lst = sorted(lst, reverse=True)
    ranks = [sorted_lst.index(x) for x in lst]
    return ranks

In [29]:
def get_rank_index(lst):
    desc_indices = [i[0] for i in sorted(enumerate(lst), key=lambda x:x[1], reverse=True)]
    ranks = [desc_indices.index(i) for i in range(len(lst))]
    return desc_indices, ranks

In [12]:
outc_weight_1 = outc_weight[1]
print(outc_weight_1)

tensor([ 1.9077e-01, -2.3996e-01, -2.2011e-01,  2.2726e-01,  1.6523e-01,
         6.2928e-02, -9.3862e-02,  1.6924e-01,  4.6609e-02,  1.7424e-01,
        -1.3293e-01, -1.4500e-01, -5.1402e-02, -1.4586e-01,  1.7412e-01,
        -2.7413e-01,  8.9397e-02, -1.5247e-01,  1.0929e-02, -1.9741e-02,
        -7.4014e-02, -2.2240e-01, -2.3658e-01, -4.9819e-02, -2.1909e-01,
         7.3912e-03, -2.4760e-01,  2.2011e-01, -2.3599e-01, -2.0199e-01,
         5.7534e-02,  2.2022e-01, -2.8642e-01,  6.6465e-02,  2.3262e-01,
        -1.1593e-01, -2.4598e-01, -1.7329e-01,  3.0668e-02,  2.1704e-01,
        -9.2812e-02,  1.6246e-01,  1.1859e-01,  3.8767e-02,  6.2464e-02,
         4.0154e-02,  1.3767e-01,  6.2940e-02, -1.1294e-01,  1.1009e-01,
         4.7192e-02,  1.7063e-01, -6.7971e-02,  2.4607e-02,  1.6709e-01,
        -2.3124e-01,  1.0113e-01,  1.7867e-01, -2.5898e-02,  8.0699e-02,
        -1.2761e-04,  6.9051e-03, -1.4364e-01,  4.2888e-02])


In [30]:
outc_weight_1_rank = get_rank(outc_weight_1)
print(outc_weight_1_rank)
outc_weight_1_rank_index, outc_weight_1_rank_index_rank = get_rank_index(outc_weight_1)
print(outc_weight_1_rank_index)
print(outc_weight_1_rank_index_rank)

[5, 59, 54, 1, 12, 22, 43, 10, 26, 7, 46, 48, 39, 49, 8, 62, 18, 50, 32, 36, 41, 55, 58, 38, 53, 33, 61, 3, 57, 52, 24, 2, 63, 20, 0, 45, 60, 51, 30, 4, 42, 13, 15, 29, 23, 28, 14, 21, 44, 16, 25, 9, 40, 31, 11, 56, 17, 6, 37, 19, 35, 34, 47, 27]
[34, 3, 31, 27, 39, 0, 57, 9, 14, 51, 7, 54, 4, 41, 46, 42, 49, 56, 16, 59, 33, 47, 5, 44, 30, 50, 8, 63, 45, 43, 38, 53, 18, 25, 61, 60, 19, 58, 23, 12, 52, 20, 40, 6, 48, 35, 10, 62, 11, 13, 17, 37, 29, 24, 2, 21, 55, 28, 22, 1, 36, 26, 15, 32]
[5, 59, 54, 1, 12, 22, 43, 10, 26, 7, 46, 48, 39, 49, 8, 62, 18, 50, 32, 36, 41, 55, 58, 38, 53, 33, 61, 3, 57, 52, 24, 2, 63, 20, 0, 45, 60, 51, 30, 4, 42, 13, 15, 29, 23, 28, 14, 21, 44, 16, 25, 9, 40, 31, 11, 56, 17, 6, 37, 19, 35, 34, 47, 27]


In [22]:
# torch.argsort()函数可以返回排序后的索引
outc_weight_11 = model.outc.weight.permute(2,3,0,1).reshape(-1,64).cpu()
print(outc_weight_11.shape)
# print(outc_weight_11)
outc_weight_rank = torch.argsort(outc_weight_11, dim=1, descending=True)
print(outc_weight_rank)

torch.Size([2, 64])
tensor([[36, 61, 42, 34, 48, 33, 63, 21, 45, 38,  9, 18, 27, 30,  2,  8, 41, 52,
         11,  3, 53, 58, 16, 44, 51, 12,  4, 24, 19, 15, 59,  6, 13, 62, 22, 50,
         60, 46, 37,  1, 23, 49, 20, 43, 26, 40, 10, 35, 47, 29, 28, 56, 31, 25,
         32, 54, 57, 39, 17,  0, 55,  5, 14,  7],
        [34,  3, 31, 27, 39,  0, 57,  9, 14, 51,  7, 54,  4, 41, 46, 42, 49, 56,
         16, 59, 33, 47,  5, 44, 30, 50,  8, 63, 45, 43, 38, 53, 18, 25, 61, 60,
         19, 58, 23, 12, 52, 20, 40,  6, 48, 35, 10, 62, 11, 13, 17, 37, 29, 24,
          2, 21, 55, 28, 22,  1, 36, 26, 15, 32]])


In [33]:
# torch.argsort()函数可以返回排序后的索引
outc_weight_11 = model.outc.weight.permute(2,3,0,1).reshape(-1,64).cpu()[1].tolist()
# print(outc_weight_11.shape)
print(outc_weight_11)
desc_indices, ranks = get_rank_index(outc_weight_11)
print(desc_indices)

[0.19076581299304962, -0.23995591700077057, -0.22011210024356842, 0.22725923359394073, 0.1652286797761917, 0.06292828917503357, -0.09386224299669266, 0.1692420244216919, 0.04660893976688385, 0.17423899471759796, -0.13293100893497467, -0.1449960470199585, -0.05140240490436554, -0.14586248993873596, 0.17411907017230988, -0.27413246035575867, 0.08939661085605621, -0.15246659517288208, 0.010929446667432785, -0.01974073238670826, -0.07401397079229355, -0.22240351140499115, -0.23657864332199097, -0.049819089472293854, -0.21908847987651825, 0.007391168735921383, -0.2475987821817398, 0.22011376917362213, -0.23599427938461304, -0.20199012756347656, 0.0575338713824749, 0.22021885216236115, -0.2864185869693756, 0.06646482646465302, 0.23261895775794983, -0.11593496054410934, -0.24597793817520142, -0.17328879237174988, 0.030667651444673538, 0.21703970432281494, -0.09281167387962341, 0.1624569296836853, 0.11858554929494858, 0.03876741603016853, 0.06246392801403999, 0.04015398770570755, 0.13766527175

In [15]:
outc_weight_0 = outc_weight[0]
out_weight_0_rank = get_rank(outc_weight_0)
print(out_weight_0_rank)

[59, 39, 14, 19, 26, 61, 31, 63, 15, 10, 46, 18, 25, 32, 62, 29, 22, 58, 11, 28, 42, 7, 34, 40, 27, 53, 44, 12, 50, 49, 13, 52, 54, 5, 3, 47, 0, 38, 9, 57, 45, 16, 2, 43, 23, 8, 37, 48, 4, 41, 35, 24, 17, 20, 55, 60, 51, 56, 21, 30, 36, 1, 33, 6]
