In [1]:
import torch
from scipy.linalg import sqrtm

def covariance_matrix(tensor1, tensor2):
    # 计算均值
    mean1 = torch.mean(tensor1, dim=0)
    mean2 = torch.mean(tensor2, dim=0)

    # 去均值化
    tensor1_centered = tensor1 - mean1
    tensor2_centered = tensor2 - mean2

    # 计算协方差矩阵
    cov_matrix = torch.mm(tensor1_centered.t(), tensor2_centered) / (tensor1_centered.shape[0] - 1)

    return cov_matrix

In [2]:
real_features = torch.tensor([[[[1., 2]],

                                [[2, 4]],

                                [[1, 2]],

                                [[3, 4]]]])
fake_features = torch.tensor([[[[1., 2]],

                                [[3, 4]],

                                [[1, 2]],

                                [[3, 4]]]])
real_features_permute = real_features.permute(0, 2, 3, 1).reshape(-1, 4)
print("\nreal_features_permute: \n", real_features_permute)
sigma_real = torch.cov(real_features_permute.t())
print("\nsigma_real: \n", sigma_real)

fake_features_permute = fake_features.permute(0, 2, 3, 1).reshape(-1, 4)
print("\nfake_features_permute: \n", fake_features_permute)
sigma_fake = torch.cov(fake_features_permute.t())
print("\nsigma_fake: \n",sigma_fake)

# print("covariance_matrix(real_features_permute, real_features_permute)\n", covariance_matrix(real_features_permute, real_features_permute))
# print("covariance_matrix(real_features_permute, fake_features_permute)\n", covariance_matrix(real_features_permute, fake_features_permute))

mu_real = torch.mean(real_features_permute, dim=0)
print("\nmu_real: \n", mu_real)
mu_fake = torch.mean(fake_features_permute, dim=0)
print("\nmu_fake: \n", mu_fake)



real_features_permute: 
 tensor([[1., 2., 1., 3.],
        [2., 4., 2., 4.]])

sigma_real: 
 tensor([[0.5000, 1.0000, 0.5000, 0.5000],
        [1.0000, 2.0000, 1.0000, 1.0000],
        [0.5000, 1.0000, 0.5000, 0.5000],
        [0.5000, 1.0000, 0.5000, 0.5000]])

fake_features_permute: 
 tensor([[1., 3., 1., 3.],
        [2., 4., 2., 4.]])

sigma_fake: 
 tensor([[0.5000, 0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000, 0.5000]])

mu_real: 
 tensor([1.5000, 3.0000, 1.5000, 3.5000])

mu_fake: 
 tensor([1.5000, 3.5000, 1.5000, 3.5000])


In [4]:
# 
import numpy as np

sigma_dot = torch.mm(sigma_real, sigma_fake)
print("\nsigma_dot: \n", sigma_dot)
# 
# print("\nsigma_real @ sigma_fake \n", sigma_real @ sigma_fake)

sqrt_sigma_dot = sqrtm(sigma_dot)
print("\nsqrt_sigma_dot: \n", sqrt_sigma_dot)
if np.iscomplexobj(sqrt_sigma_dot):
    sqrt_sigma_dot = sqrt_sigma_dot.real

tr_cov = torch.trace(sigma_real + sigma_fake - 2 * sqrt_sigma_dot)
print(tr_cov)


sigma_dot: 
 tensor([[1.2500, 1.2500, 1.2500, 1.2500],
        [2.5000, 2.5000, 2.5000, 2.5000],
        [1.2500, 1.2500, 1.2500, 1.2500],
        [1.2500, 1.2500, 1.2500, 1.2500]])

sqrt_sigma_dot: 
 [[0.50000006+5.5242702e-04j 0.49999988-1.2990915e-04j
  0.49999994-1.5482033e-04j 0.4999999 -1.3778846e-04j]
 [0.9999998 -2.7621354e-04j 0.99999946+1.1982386e-04j
  0.9999996 +2.2540897e-05j 0.9999995 +1.4024959e-05j]
 [0.5       -1.3810680e-04j 0.49999982+5.0426461e-06j
  0.49999988+6.6139743e-05j 0.49999985+6.1881772e-05j]
 [0.5       -1.3810680e-04j 0.49999982+5.0426461e-06j
  0.49999988+6.6139743e-05j 0.49999985+6.1881772e-05j]]
tensor(0.5000)


In [12]:
# x =  torch.tensor([-1.0, -4], dtype=torch.complex64)
# sqrt_x = torch.sqrt(x)
# print(sqrt_x)
# print(sqrt_x.dtype)
# real_part = sqrt_x.real
# print(real_part)
# print(real_part.dtype)

tensor([0.+1.j, 0.+2.j])
torch.complex64
tensor([0., 0.])
torch.float32


In [5]:
# fid = ssdiff + np.trace(sigma_real + sigma_fake - 2.0 * covmean)
# F范数
mean_F_norm = torch.norm(mu_real - mu_fake, p=2).item()
print("\nmean_F_norm: \n", mean_F_norm)


mean_F_norm: 
 0.5
