In [6]:
# example of calculating the frechet inception distance
import numpy as np
# from numpy import cov
# from numpy import trace
# from numpy import iscomplexobj
# from numpy.random import random
from scipy.linalg import sqrtm

# calculate frechet inception distance
def calculate_fid(act1, act2):
	# calculate mean and covariance statistics
	mu1, sigma1 = act1.mean(axis=0), np.cov(act1, rowvar=False)
	mu2, sigma2 = act2.mean(axis=0), np.cov(act2, rowvar=False)
	print("sigma1.dtype: ", sigma1.dtype)
	# calculate sum squared difference between means
	ssdiff = np.sum((mu1 - mu2)**2.0)
	print("\nssdiff: \n", ssdiff)
	print("\nssdiff.dtype: \n", ssdiff.dtype)
	# calculate sqrt of product between cov
	covmean = sqrtm(sigma1.dot(sigma2))
	print("sigma1: \n", sigma1)
	print("\nsigma2: \n", sigma2)
	print("\nsigma1.dot(sigma2): \n", sigma1.dot(sigma2))
	print("\ncovmean: \n", covmean)
	# check and correct imaginary numbers from sqrt
	if np.iscomplexobj(covmean):
		covmean = covmean.real
	# calculate score
	fid = ssdiff + np.trace(sigma1 + sigma2 - 2.0 * covmean)
	print("\nfid.dtype: \n", fid.dtype)
	return fid

# define two collections of activations
# act1 = random(4*4)
act1 = np.array([[1., 1., 1., 3.],
        [2., 4., 2., 4.]])
act1 = act1.reshape((-1,4))
# act2 = random(4*4)
act2 = np.array([[1., 3., 1., 3.],
        [2., 4., 2., 4.]])
act2 = act2.reshape((-1,4))
# fid between act1 and act1
fid = calculate_fid(act1, act1)
print('FID (same): %.3f' % fid)
# fid between act1 and act2
fid = calculate_fid(act1, act2)
print('FID (different): %.3f' % fid)
print("fid.dtype: ", fid.dtype)

sigma1.dtype:  float64

ssdiff: 
 0.0

ssdiff.dtype: 
 float64
sigma1: 
 [[0.5 1.5 0.5 0.5]
 [1.5 4.5 1.5 1.5]
 [0.5 1.5 0.5 0.5]
 [0.5 1.5 0.5 0.5]]

sigma2: 
 [[0.5 1.5 0.5 0.5]
 [1.5 4.5 1.5 1.5]
 [0.5 1.5 0.5 0.5]
 [0.5 1.5 0.5 0.5]]

sigma1.dot(sigma2): 
 [[ 3.  9.  3.  3.]
 [ 9. 27.  9.  9.]
 [ 3.  9.  3.  3.]
 [ 3.  9.  3.  3.]]

covmean: 
 [[0.5+0.00000000e+00j 1.5-8.98573829e-09j 0.5+1.34786073e-08j
  0.5+1.34786075e-08j]
 [1.5+0.00000000e+00j 4.5+8.98573829e-09j 1.5-1.34786074e-08j
  1.5-1.34786075e-08j]
 [0.5+0.00000000e+00j 1.5-8.98573829e-09j 0.5+1.34786076e-08j
  0.5+1.34786073e-08j]
 [0.5+0.00000000e+00j 1.5-8.98573829e-09j 0.5+1.34786073e-08j
  0.5+1.34786076e-08j]]

fid.dtype: 
 float64
FID (same): -0.000
sigma1.dtype:  float64

ssdiff: 
 1.0

ssdiff.dtype: 
 float64
sigma1: 
 [[0.5 1.5 0.5 0.5]
 [1.5 4.5 1.5 1.5]
 [0.5 1.5 0.5 0.5]
 [0.5 1.5 0.5 0.5]]

sigma2: 
 [[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]

sigma1.dot(sigma2): 
 [[1.5 1