In [1]:
import torch

# 示例张量
tensor = torch.tensor([[1, 2, 3, 0], 
                       [5, 6, 0, 8], 
                       [0, 10, 0, 0],
                       ], dtype=torch.float)

# 创建一个布尔掩码，标记不应忽略的值
mask = tensor != 0

# 输出张量和掩码
print(tensor)
print(tensor[mask])

# 计算张量的平均值
mean_val_original = torch.mean(tensor, dim=0)
print(mean_val_original)

# 使用掩码选择张量中的值，并计算平均值
mean_val = torch.mean(tensor[mask])
print(mean_val)


masked_tensor = torch.zeros(tensor.shape[1], dtype=torch.float)
for i in range(tensor.shape[1]):
    mask = tensor[:, i] != 0.0
    mean_val = torch.mean(tensor[mask, i])
    if not torch.isnan(mean_val):
        masked_tensor[i] = mean_val

print(masked_tensor)

tensor([[ 1.,  2.,  3.,  0.],
        [ 5.,  6.,  0.,  8.],
        [ 0., 10.,  0.,  0.]])
tensor([ 1.,  2.,  3.,  5.,  6.,  8., 10.])
tensor([2.0000, 6.0000, 1.0000, 2.6667])
tensor(5.)
tensor([3., 6., 3., 8.])
