In [1]:
from torchmetrics.functional.classification import multiclass_precision
from torchmetrics.functional.classification import multiclass_recall
from torchmetrics.functional.classification import multiclass_f1_score


In [22]:
import torch
predictions = [0, 0, 0, 0, 1, 1, 1, 1]
labels = [0, 0, 1, 1, 0, 1, 1, 1]
num_classes = 2
ignore_index = None
precision = multiclass_precision(torch.tensor(predictions), torch.tensor(labels), num_classes, "none", ignore_index=ignore_index)
print(precision)
print((2/4 + 3/4) / 2)

tensor([0.5000, 0.7500])
0.625


In [8]:
import torch
predictions = [0, 0, 0, 1, 1, 1, 1, 1, 1]
labels =      [0, 0, 1, 1, 0, 1, 1, 1, 1]
num_classes = 2
ignore_index = 0
precision = multiclass_precision(torch.tensor(predictions), torch.tensor(labels), num_classes, "none", ignore_index=ignore_index)
recall = multiclass_recall(torch.tensor(predictions), torch.tensor(labels), num_classes, "none", ignore_index=ignore_index)
f1 = multiclass_f1_score(torch.tensor(predictions), torch.tensor(labels), num_classes, "none", ignore_index=ignore_index)
print(precision)
print(recall)
print(f1)
precision = multiclass_precision(torch.tensor(predictions), torch.tensor(labels), num_classes, "micro", ignore_index=ignore_index)
recall = multiclass_recall(torch.tensor(predictions), torch.tensor(labels), num_classes, "micro", ignore_index=ignore_index)
f1 = multiclass_f1_score(torch.tensor(predictions), torch.tensor(labels), num_classes, "micro", ignore_index=ignore_index)
print(precision)
print(recall)
print(f1)
precision = multiclass_precision(torch.tensor(predictions), torch.tensor(labels), num_classes, "macro", ignore_index=ignore_index)
recall = multiclass_recall(torch.tensor(predictions), torch.tensor(labels), num_classes, "macro", ignore_index=ignore_index)
f1 = multiclass_f1_score(torch.tensor(predictions), torch.tensor(labels), num_classes, "macro", ignore_index=ignore_index)
print(precision)
print(recall)
print(f1)
# print((2/4 + 3/4) / 2)

tensor([0., 1.])
tensor([0.0000, 0.8333])
tensor([0.0000, 0.9091])
tensor(0.8333)
tensor(0.8333)
tensor(0.8333)
tensor(0.5000)
tensor(0.4167)
tensor(0.4545)
