In [1]:
import torch

# Create a tensor
x = torch.tensor([1.0, 2.0, 3.0, 4.0])

# Compute the F2 norm
f2_norm = torch.norm(x, p=2)

print(f2_norm)

tensor(5.4772)


In [3]:
import torch
a = torch.tensor([[1.0, 2.0], 
                  [3.0, 4.0]])
b = torch.tensor([[5.0, 6.0], 
                  [7.0, 8.0]])
# print(a @ b)
# print(a.t() @ b.t())
print(a[1, :])

tensor([3., 4.])


In [5]:
list1 = [1, 2, 3, 4]
feature = []
for i in range(2):
    feature.append(list1)
print(feature)
all = []
for i in range(2):
    all = all+feature

print(all)

[[1, 2, 3, 4], [1, 2, 3, 4]]
[[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]]


In [2]:
import numpy as np

# 示例数据：两个变量，每个变量有五个观测
data = np.array([[1, 2, 3, 4],
                 [4, 3, 2, 1]])

# 计算协方差矩阵
cov_matrix = np.cov(data, rowvar=False)

print(cov_matrix)

[[ 8.  4.  0. -4. -8.]
 [ 4.  2.  0. -2. -4.]
 [ 0.  0.  0.  0.  0.]
 [-4. -2.  0.  2.  4.]
 [-8. -4.  0.  4.  8.]]


In [1]:
import numpy as np
from scipy.linalg import sqrtm

# 示例二维数据矩阵，假设我们要忽略0值
data = np.array([[1., 2, 3, 4],
                 [4, 0, 2, 1],])

# 将0值替换为np.nan
data_with_nan = np.where(data == 0, np.nan, data)

# 创建掩码数组，自动将np.nan视为掩码
masked_data = np.ma.array(data_with_nan, mask=np.isnan(data_with_nan))
print(masked_data)

mean_matrix = np.ma.mean(masked_data, axis=0)
print(mean_matrix)

# 计算掩码数组的协方差矩阵
cov_matrix = np.ma.cov(masked_data, rowvar=False)
print(cov_matrix)

sigma1 = np.ma.filled(cov_matrix, 0)
covmean = sqrtm(sigma1.dot(sigma1))
print(covmean)

print(np.trace(cov_matrix))

[[1.0 2.0 3.0 4.0]
 [4.0 -- 2.0 1.0]]
[2.5 2.0 2.5 2.5]
[[4.5 -- -1.5 -4.5]
 [-- -- -- --]
 [-1.5 -- 0.5 1.5]
 [-4.5 -- 1.5 4.5]]
[[ 4.5       +4.43651037e-08j  0.        +0.00000000e+00j
  -1.5       +1.26757439e-08j -4.5       +4.01398557e-08j]
 [ 0.        +0.00000000e+00j  0.        +0.00000000e+00j
   0.        +0.00000000e+00j  0.        +0.00000000e+00j]
 [-1.5       +1.33095311e-08j  0.        +0.00000000e+00j
   0.50000002+3.80272317e-09j  1.49999999+1.20419567e-08j]
 [-4.5       +3.99285933e-08j  0.        +0.00000000e+00j
   1.49999999+1.14081695e-08j  4.5       +3.61258702e-08j]]
9.5


In [3]:
import numpy as np
from scipy.linalg import sqrtm

# 示例二维数据矩阵，假设我们要忽略0值
data = np.array([[1., 0, 3, 4],
                 [4, 0, 2, 1],])

data2 = np.array([[1., 16, 3, 4],
                    [4, 0, 2, 1],])


# 创建掩码数组，自动将0视为掩码
masked_data = np.ma.array(data, mask=np.where(data == 0.0, True, False))
print(masked_data)

mean_matrix = np.ma.mean(masked_data, axis=0)
mean_matrix = np.ma.filled(mean_matrix, 0)
mean_matrix2 = np.ma.mean(data2, axis=0)
ssdiff = np.sum((mean_matrix - mean_matrix2)**2.0)
print(mean_matrix, mean_matrix2)
print("ssdiff:",ssdiff)

# 计算掩码数组的协方差矩阵
cov_matrix = np.ma.cov(masked_data, rowvar=False)
print(cov_matrix)

sigma1 = np.ma.filled(cov_matrix, 0)
covmean = sqrtm(sigma1.dot(sigma1))
print(covmean)

print(np.trace(cov_matrix))

[[1.0 -- 3.0 4.0]
 [4.0 -- 2.0 1.0]]
[2.5 0.  2.5 2.5] [2.5 8.  2.5 2.5]
ssdiff: 64.0
[[4.5 -- -1.5 -4.5]
 [-- -- -- --]
 [-1.5 -- 0.5 1.5]
 [-4.5 -- 1.5 4.5]]
[[ 4.5       +4.43651037e-08j  0.        +0.00000000e+00j
  -1.5       +1.26757439e-08j -4.5       +4.01398557e-08j]
 [ 0.        +0.00000000e+00j  0.        +0.00000000e+00j
   0.        +0.00000000e+00j  0.        +0.00000000e+00j]
 [-1.5       +1.33095311e-08j  0.        +0.00000000e+00j
   0.50000002+3.80272317e-09j  1.49999999+1.20419567e-08j]
 [-4.5       +3.99285933e-08j  0.        +0.00000000e+00j
   1.49999999+1.14081695e-08j  4.5       +3.61258702e-08j]]
9.5


In [2]:
import torch
extracted_features_tensor_dict = {0: torch.tensor([[1.0, 2.0],[3.0, 4.0]]), 
                                  1: torch.tensor([[5.0, 6.0],[7.0, 8.0]])}
num_classes = 2
feature_mean_all = torch.mean(torch.cat([extracted_features_tensor_dict[i] for i in range(num_classes)], dim=0), dim=0)
print(torch.cat([extracted_features_tensor_dict[i] for i in range(num_classes)], dim=0))
print(feature_mean_all)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([4., 5.])


In [3]:
last_layer_weight_1 = [1., 2., 3., 4.]
print(f"last_layer_weight_1: {last_layer_weight_1}")
last_layer_weight_1_normalized = [i/sum(last_layer_weight_1) for i in last_layer_weight_1]
print(f"last_layer_weight_1_normalized: {last_layer_weight_1_normalized}")

last_layer_weight_1: [1.0, 2.0, 3.0, 4.0]
last_layer_weight_1_normalized: [0.1, 0.2, 0.3, 0.4]
